fix bug in autotools where Thread-Local Storage isn't detected because of undefined identifier 'NULL'
without this, autotools fails with:
conftest.cpp:31:72: error: use of undeclared identifier 'NULL' template<typename T>  __thread  T* TLSClass<T>::tlsvar = NULL;